/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentevisualpersonalizado;

import java.awt.Color;
import java.awt.Font;
import java.io.Serializable;
import static javax.swing.BorderFactory.createLineBorder;
import javax.swing.border.Border;
import org.apache.commons.validator.routines.EmailValidator;



/**
 *
 * @author agalmad
 */
public class Email extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form Email
     */
        
    private Color borderErrorColor = Color.RED;
    private Color borderNormalColor = Color.BLACK;
    

    //Cambiar Color del texto de error
    public Color getErrorColor() {
        return jLabelError.getForeground();
    }

    public void setErrorColor(Color errorColor) {
        jLabelError.setForeground(errorColor);
    }

    //Cambiar el color del texto del email
    public Color getEmailTextColor() {
        return jTextFieldEmail.getForeground();
    }

    public void setEmailTextColor(Color emailColor) {
        jTextFieldEmail.setForeground(emailColor);
    }


    //Método para cambiar el color del borde del text fiel
    public void setBorderColor(Color emailBorderColor) {
        jTextFieldEmail.setBorder(createLineBorder(emailBorderColor,1,false));
    }

    //Cambiar el color del borde cuando da error
    public Color getBorderErrorColor() {
        return borderErrorColor;
    }

    public void setBorderErrorColor(Color borderErrorColor) {
        this.borderErrorColor = borderErrorColor;
    }

    //Cambiar el color del borde cuando no existen errores
    public Color getBorderNormalColor() {
        return borderNormalColor;
    }

    public void setBorderNormalColor(Color borderNormalColor) {
        this.borderNormalColor = borderNormalColor;
    }

   
    
    
    //Cambiar Fuente del error
    public Font getErrorFont() {
        return jLabelError.getFont();
    }

    public void setErrorFont(Font errorFont) {
        jLabelError.setFont(errorFont);
    }
    
    //Cambiar Fuente del email
    public Font getEmailFont() {
        return jTextFieldEmail.getFont();
    }

    public void setEmailFont(Font emailFont) {
        jTextFieldEmail.setFont(emailFont);
    }
    
    
    
    //Cambiar el texto del error
    public String getErrorText() {
        return jLabelError.getText();
    }

    public void setErrorText(String errorText) {
        jLabelError.setText(errorText);
    }

    //Cambiar el texto del email
    public String getEmailText() {
        return jTextFieldEmail.getText();
    }

    public void setEmailText(String emailText) {
        jTextFieldEmail.setText(emailText);
    }
    
    
    //Hint
    //Cambiar el texto del hint
    public String getHintText() {
        return jLabelHint.getText();
    }

    public void setHintText(String hintText) {
        jLabelHint.setText(hintText);
    }
    
    //Cambiar Color del texto de hint
    public Color getHintColor() {
        return jLabelHint.getForeground();
    }

    public void setHintColor(Color hintColor) {
        jLabelHint.setForeground(hintColor);
    }
    
    //Cambiar Fuente del error
    public Font getHintFont() {
        return jLabelHint.getFont();
    }

    public void setHintFont(Font hintFont) {
        jLabelHint.setFont(hintFont);
    }
    
    
    public Email() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHint = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHint.setForeground(new java.awt.Color(102, 102, 102));
        jLabelHint.setText("tunombre@ejemplo.es");
        add(jLabelHint, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 328, -1));

        jTextFieldEmail.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldEmail.setToolTipText("");
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });
        jTextFieldEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldEmailMouseClicked(evt);
            }
        });
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyReleased(evt);
            }
        });
        add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 6, 333, 30));

        jLabelError.setForeground(new java.awt.Color(204, 0, 0));
        jLabelError.setText("Email Incorrecto");
        add(jLabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 320, -1));
        jLabelError.setVisible(false);

        jLabel1.setText("Correo :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyPressed
        

    }//GEN-LAST:event_jTextFieldEmailKeyPressed

    private void jTextFieldEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEmailMouseClicked
    }//GEN-LAST:event_jTextFieldEmailMouseClicked

    private void jTextFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusGained
        jLabelHint.setVisible(false);

    }//GEN-LAST:event_jTextFieldEmailFocusGained

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        if (jTextFieldEmail.getText().equals("")) {
            jLabelHint.setVisible(true);

        }
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jTextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyReleased
        if(emailValidator(jTextFieldEmail.getText())){
            jLabelError.setVisible(false);
            setBorderColor(borderNormalColor);

        }
        else{
            jLabelError.setVisible(true);
            setBorderColor(borderErrorColor);

        }
    }//GEN-LAST:event_jTextFieldEmailKeyReleased


    // Validar una dirección de correo electrónico usando el validador
    public static boolean emailValidator(String email)
    {
        // Obtener una instancia de la clase EmailValidator
        EmailValidator validator = EmailValidator.getInstance();
 
        // Devuelve verdadero si la dirección de correo electrónico es válida
        return validator.isValid(email);
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelHint;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables
}
